{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "springboot-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "springboot-service.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "springboot-service.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Permitir tráfico desde el mismo namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.namespace }}
  # Permitir tráfico desde namespaces de sistema
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - namespaceSelector:
        matchLabels:
          name: istio-system
  egress:
  # Permitir DNS
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  {{- if .Values.networkPolicy.allowEgressWeb }}
  # Permitir HTTP/HTTPS saliente
  - to: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  {{- end }}
  # Permitir tráfico al mismo namespace
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.namespace }}
{{- end }}
