apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "springboot-service.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  {{- if .Values.serviceMonitor.enabled }}
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    {{- include "springboot-service.selectorLabels" . | nindent 4 }}
