apiVersion: v2
appVersion: 1.0.0
description: Chart genérico para servicios Spring Boot con observabilidad y seguridad
home: https://github.com/lostreseditores/helm-charts
keywords:
- springboot
- java
- microservice
maintainers:
- email: tecnologia@lostreseditores.com
  name: Platform Team
name: springboot-service
sources:
- https://github.com/lostreseditores/helm-charts
type: application
version: 0.1.3
