name: Release Helm Chart

on:
  push:
    tags:
      - 'chart/springboot-service/v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Package Chart
      run: |
        helm package charts/springboot-service/
        ls -la *.tgz

    - name: Update Index
      run: |
        # Crear directorio gh-pages si no existe
        mkdir -p gh-pages
        
        # Si existe el branch gh-pages, clonarlo
        if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
          git clone --branch gh-pages --single-branch https://github.com/${{ github.repository }}.git gh-pages
        else
          mkdir -p gh-pages
          cd gh-pages
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          cd ..
        fi
        
        # Mover charts a gh-pages
        mv *.tgz gh-pages/
        
        # Actualizar index
        cd gh-pages
        helm repo index . --url https://${{ github.repository_owner }}.github.io/helm-charts
        
        # Configurar git
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Commit y push
        git add .
        git commit -m "Release springboot-service ${{ github.ref_name }}"
        git push origin gh-pages

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/gh-pages'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
